### ISSUE TITLE
DC lecture slides on schedule

### ISSUE THREAD

**Issue by lheagy** [ubcgif/eosc350website#129]
The lecture slides for DC resistivity need to be posted on the course schedule yet. The have been uploaded to:  
https://github.com/ubcgif/eosc350website/blob/master/assets/6_DC/9_DC_Resistivity.pdf 

![image](https://cloud.githubusercontent.com/assets/6361812/20539431/d0a57e50-b0a9-11e6-95c3-21144cbf24f9.png)

@thast: would you mind taking care of this? Thanks!

**Comment by thast** [comment]
#130
